basePath: /api/V1
host: http://localhost:8080
info:
  contact:
    email: m.dehghanpour
    name: mohammad dehghanpour
  description: This is a restapi for video management
  title: test gin framework
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
